server:
  port: ${PORT:8081}
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
   name: logos_api

  jackson:
    serialization:
      indent-output: true
    default-property-inclusion: NON_NULL

logging:
  level:
    root: INFO
    io.github.logos_api: DEBUG